server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: sudhir
    password: sudhir123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  jpa.properties.hibernate.format_sql: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
jwt:
  secret: "J8dK2pR6uS9vX1bQ4fT7zM0cN3hW5eY8aD6gJ2kP4rU7wQ1xL9vB3nT0sV5mZ8ab"
  expiration: 3600000

